### ISSUE TITLE
Base Tests

### ISSUE THREAD

**Issue by dyiop** [usnistgov/ATICC#11]
# User Story:

As an ATICC user, I need to easily create each each type of base test to fulfill my overall testing outline. 

## Goals:

A user should be able to easily add and remove various base tests via the dashboard. A user will use this capability to implement their testing outline in the dashboard itself. The execution code for each test will be in the coordinator, and the response will be analyzed in the dashboard to determine whether the test passed or failed. The user will then be preseneted with an explanation of result.

## Dependencies:
- [ ] Finalize list of base tests
- [ ] Coordinator Things
    - [ ] Implement each base test (#6)
    - [ ] Make a new rest endpoint for each base test (#6)
- [ ] Dashboard Things
    - [ ] Make handler for each test
        - [ ] Send corresponding REST Request
        - [ ] Analyze response to determine pass/fail and explanation

## Acceptance Criteria

- [ ] Dependencies completed
- [ ] Usage testing done to discover new bugs and features.

**Comment by nikitawootten-nist** [comment]
With the shift towards InSpec profiles, all coordinator/dashboard issues are now out of scope.
