### ISSUE TITLE
Dashboard-driven Test Suite Architecture

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/ATICC#2]
# User Story:

As an ATICC developer, I need to have a well-defined architecture of the Dashboard-driven testing suite.

## Goals:

The Dashboard-driven test suite's architecture is final so the implementation can commence.
It should define all of information necessary to complete development including, but not limited to:
- [x] The overall architecture (Architecture.md)
- [ ] Test Types ()

## Dependencies:
#3 List of Test Types

## Acceptance Criteria

- [ ] The architecture supports all use case scenarios that demonstrate TIC 3.0 functionality.
- [ ] All the parts listed above are complete to reflect the current state of the architecture. Each are stored in the listed file in the Doc folder.

**Comment by iMichaela** [comment]
## 10/07/2020

@dyiop - please update this Epic issue and link it to the individual user stories per the minutes of the meeting. @nikitawootten-nist, please help Akash.
