### ISSUE TITLE
List of Test Types

### ISSUE THREAD

**Issue by dyiop** [usnistgov/ATICC#3]
# User Story:

As an ATICC Developer, I need to define what types of tests are going to be implemented.

## Goals:

Looking through the testing outline, make a concise but complete list of test types that the Dashboard can initiate and the Coordinator can execute. For each test we need this information:
- Name: A short name which describes the test
    - Example: _Ping Test_
- Execution Parameters: Configurable parameters which lets the test type be used for many actual tests. Each Parameter should have a name and data type
    - Example:
        1. _IP_: `String`
- Execution Process: The actual plan on how to implement this test.
    - Example: Ping the IP address given in parameter _IP_
- Completion Data: The data received at the end of the test, which will then be sent to dashboard for analysis.
    - Example:
        1. _Success_: `Boolean`

## Dependencies:

- [x] Further divide rows for tests that need to be split up (e.g. ingest, transit, egress & positive/negative results)
    -  During development, keep in mind some tests will have a positive case and a negative case
- [ ] Broaden the tests to be more thorough (e.g. tests do not depend on ATARC implementation, generalize) (#9)
- [ ] Complete the 'SDP Config Check' column (#8)
- [ ] Fill in how the pilot addresses each TIC requirement in the 'The Pilot Solution' column
- [ ] Assign a base test to each row. (Ex. Packet + Request for Access Control - Ingest)

## Acceptance Criteria

- [ ] A complete list of test types, with the specified info for each one, stored somewhere in the Docs folder
- [ ] Should be able to cover all of the actual tests listed in the testing outline.
- [ ] Dashboard should have empty placeholders for each test type.
