### ISSUE TITLE
Coordinator Communication with Dashboard

### ISSUE THREAD

**Issue by dyiop** [usnistgov/ATICC#5]
# User Story:

As a ATICC Developer, I need to know how the Coordinator and Dashboard will communicate.

## Goals:

Create and define the REST API that will be used by the dashboard in order to:

1. Start the the various tests.

2. Get the results of the tests from the point of view of clients. The Dashboard can then consult the SDP controller to further assess the results of the tests.

[Here](https://github.com/usnistgov/ATICC/files/5394463/ATICC.Architechture.pdf) is a PDF further describing the flow in more detail.

## Dependencies:

- Planning:
    - [ ]  Decide what exact rest API endpoints we're going to need.
        - [ ]  Set up which tests are going to have which configurations (#3)
- Development:
    - [x]  Create the GO project
    - [x]  Create the GO REST Server
    - [x]  Implement REST communication in Java for sending requests to the coordinator from the dasboard
    - [ ]  Set Endpoint names (one for each test?), and which configuration parameters they are going to have
        - [ ]  Endpoint 1
        - [ ]  Endpoint 2
        - [ ]  Endpoint 3 

## Acceptance Criteria

 - [ ]

**Comment by nikitawootten-nist** [comment]
With the shift towards InSpec profiles, all coordinator/dashboard issues are now out of scope.
