### ISSUE TITLE
Coordinator: Test Execution

### ISSUE THREAD

**Issue by dyiop** [usnistgov/ATICC#6]
# User Story:

As a ATICC Developer, I need to know how the coordinator will execute the tests.

## Goals:

Along with communicating with the dashboard, the coordinator should be able to execute the tests. This entails:

- *Creating and destroying any necessary Client VM's for each test.*
    - The coordinator should also be able to facilitate any necessary communication between the two clients.
    - The coordinator will create the Client VM's though docker.
- *Actually execution of tests.*
    - Once each Client VM is created, the coordinator will run the tests on the Client VM's.
    - The coordinator will be only place with the actual implementation of each test, although both parts (dashboard and coordinator) will need to know the meta information for the tests in order to communicate correctly.

## Dependencies:

- Planning:
    - [ ]  Decide what kind of tests are needed.  (#3)
        - [ ]  Decide which configuration parameters each one needs.
        - [ ]  Decide on implementation tactics for each one.
    - [ ]  Decide what OS the VM Client Images will be based on
- Development:
    - [ ]  Add docker driver to GO project (#10)
    - [ ]  Make Client VM Images
        1. Good Guy Client
            - [ ]  Install/Configuration SDP client
                - [x] Install SDP Client
                - [x] Get SSH access to gateway
                - [ ] Configure SDP Client
        2. Bad Guy Client
            - No further configuration necessary
    - [ ]  Write actual test's
        - [ ]  For each test we will have to spawn various clients and run various commands
    - [ ]  Link it to the REST api
        - [ ]  Run the corresponding test (with the given configuration) when each REST request is received.

## Acceptance Criteria

- [ ]

**Comment by nikitawootten-nist** [comment]
With the shift towards InSpec profiles, all coordinator/dashboard issues are now out of scope.
